name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v4
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v4
        with:
          node-version: "13.x"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README.md"
          file_pattern: "README.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

